package migration

import (
	"context"
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"github.com/eduardo/blueprint/internal/domain"
)

type Migration struct {
	Version     string
	Name        string
	AppliedAt   *time.Time
	RollbackSQL string
}

type MigrationFile struct {
	Version string
	Name    string
	UpSQL   string
	DownSQL string
}

type Migrator interface {
	RunMigrations(ctx context.Context) error
	Rollback(ctx context.Context, steps int) error
	GetAppliedMigrations(ctx context.Context) ([]Migration, error)
	GenerateMigrationFiles(config *domain.Config, outputDir string, fs domain.FileSystemPort) error
}

type PostgresMigrator struct {
	DBURL         string
	DatabaseType  string
	MigrationsDir string
}

type MongoMigrator struct {
	DBURL         string
	DatabaseType  string
	MigrationsDir string
}

func NewPostgresMigrator(dbURL, migrationsDir string) *PostgresMigrator {
	return &PostgresMigrator{
		DBURL:         dbURL,
		DatabaseType:  "postgresql",
		MigrationsDir: migrationsDir,
	}
}

func NewMongoMigrator(dbURL, migrationsDir string) *MongoMigrator {
	return &MongoMigrator{
		DBURL:         dbURL,
		DatabaseType:  "mongodb",
		MigrationsDir: migrationsDir,
	}
}

func (m *PostgresMigrator) RunMigrations(ctx context.Context) error {
	fmt.Println("Running PostgreSQL migrations...")
	return nil
}

func (m *PostgresMigrator) Rollback(ctx context.Context, steps int) error {
	fmt.Printf("Rolling back %d PostgreSQL migration(s)...\n", steps)
	return nil
}

func (m *PostgresMigrator) GetAppliedMigrations(ctx context.Context) ([]Migration, error) {
	fmt.Println("Fetching applied migrations from PostgreSQL...")
	return []Migration{}, nil
}

func (m *PostgresMigrator) GenerateMigrationFiles(config *domain.Config, outputDir string, fs domain.FileSystemPort) error {
	version := time.Now().Format("20060102150405")
	migrationName := "initial_schema"

	dir := filepath.Join(outputDir, "postgresql")
	if err := fs.MkdirAll(dir); err != nil {
		return fmt.Errorf("failed to create migrations directory: %w", err)
	}

	upSQL := fmt.Sprintf(`-- Migration: %s
-- Version: %s
-- Generated by Blueprint

BEGIN;

CREATE TABLE IF NOT EXISTS schema_migrations (
    version VARCHAR(14) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    applied_at TIMESTAMP NOT NULL DEFAULT NOW(),
    rollback_sql TEXT
);

`, migrationName, version)

	var downTables []string

	for _, model := range config.Models {
		var columns []string
		columns = append(columns, "id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text")

		var fieldNames []string
		for fieldName, fieldType := range model.Fields {
			columns = append(columns, fmt.Sprintf("%s %s", fieldName, mapGoTypeToPostgres(fieldType)))
			fieldNames = append(fieldNames, fieldName)
		}

		for relName, relType := range model.Relations {
			if !strings.HasPrefix(relType, "hasMany") {
				columns = append(columns, fmt.Sprintf("%s TEXT", relName))
				fieldNames = append(fieldNames, relName)
			}
		}

		if model.SoftDelete {
			columns = append(columns, "deleted_at TIMESTAMP")
		}
		columns = append(columns, "created_at TIMESTAMP DEFAULT NOW()")
		columns = append(columns, "updated_at TIMESTAMP DEFAULT NOW()")

		upSQL += fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n    %s\n);\n\n", model.Name, strings.Join(columns, ",\n    "))

		for _, relName := range fieldNames {
			if rel, ok := model.Relations[relName]; ok && strings.HasPrefix(rel, "hasMany:") {
				refModel := strings.Split(rel, ":")[1]
				upSQL += fmt.Sprintf("CREATE INDEX IF NOT EXISTS idx_%s_%s ON %s(%s);\n", model.Name, relName, model.Name, relName)
				_ = refModel
			}
		}

		downTables = append(downTables, model.Name)
	}

	upSQL += "\nCOMMIT;\n"

	downSQL := fmt.Sprintf(`-- Rollback: %s
-- Version: %s
-- Generated by Blueprint

BEGIN;

`, migrationName, version)

	for _, table := range downTables {
		downSQL += fmt.Sprintf("DROP TABLE IF EXISTS %s;\n", table)
	}
	downSQL += "DROP TABLE IF EXISTS schema_migrations;\n"
	downSQL += "\nCOMMIT;\n"

	upFilePath := filepath.Join(dir, fmt.Sprintf("%s_%s.up.sql", version, migrationName))
	downFilePath := filepath.Join(dir, fmt.Sprintf("%s_%s.down.sql", version, migrationName))

	if err := fs.WriteFile(upFilePath, []byte(upSQL)); err != nil {
		return fmt.Errorf("failed to write up migration: %w", err)
	}
	if err := fs.WriteFile(downFilePath, []byte(downSQL)); err != nil {
		return fmt.Errorf("failed to write down migration: %w", err)
	}

	fmt.Printf("Generated PostgreSQL migration: %s\n", upFilePath)
	return nil
}

func mapGoTypeToPostgres(fieldType string) string {
	switch fieldType {
	case "int", "integer":
		return "INTEGER"
	case "float", "double":
		return "DOUBLE PRECISION"
	case "boolean", "bool":
		return "BOOLEAN"
	case "datetime", "time":
		return "TIMESTAMP"
	case "text":
		return "TEXT"
	default:
		return "TEXT"
	}
}

func (m *MongoMigrator) RunMigrations(ctx context.Context) error {
	fmt.Println("Running MongoDB migrations...")
	return nil
}

func (m *MongoMigrator) Rollback(ctx context.Context, steps int) error {
	fmt.Printf("Rolling back %d MongoDB migration(s)...\n", steps)
	return nil
}

func (m *MongoMigrator) GetAppliedMigrations(ctx context.Context) ([]Migration, error) {
	fmt.Println("Fetching applied migrations from MongoDB...")
	return []Migration{}, nil
}

type mongoIndex struct {
	Name   string
	Fields string
}

func (m *MongoMigrator) GenerateMigrationFiles(config *domain.Config, outputDir string, fs domain.FileSystemPort) error {
	version := time.Now().Format("20060102150405")
	migrationName := "initial_schema"

	dir := filepath.Join(outputDir, "mongodb")
	if err := fs.MkdirAll(dir); err != nil {
		return fmt.Errorf("failed to create migrations directory: %w", err)
	}

	var allIndexes []mongoIndex
	for _, model := range config.Models {
		for relName, relType := range model.Relations {
			if strings.HasPrefix(relType, "hasMany") {
				parts := strings.Split(relType, ":")
				if len(parts) == 2 {
					idx := mongoIndex{
						Name:   relName + "_" + parts[1],
						Fields: fmt.Sprintf(`"%s": 1`, relName),
					}
					allIndexes = append(allIndexes, idx)
				}
			}
		}
	}

	upSQL := fmt.Sprintf(`// Migration: %s
// Version: %s
// Generated by Blueprint

// Schema migrations collection
db.createCollection("schema_migrations");

db.schema_migrations.createIndex({ "_version": 1 }, { unique: true });

`, migrationName, version)

	for _, model := range config.Models {
		upSQL += fmt.Sprintf(`// Collection: %s
db.createCollection("%s");

db.%s.createIndex({ "_id": 1 });

`, model.Name, model.Name, model.Name)

		for _, idx := range allIndexes {
			upSQL += fmt.Sprintf(`db.%s.createIndex({ %s }, { name: "idx_%s" });

`, model.Name, idx.Fields, idx.Name)
		}
	}

	downSQL := fmt.Sprintf(`// Rollback: %s
// Version: %s
// Generated by Blueprint

db.schema_migrations.drop();

`, migrationName, version)

	upFilePath := filepath.Join(dir, fmt.Sprintf("%s_%s.up.js", version, migrationName))
	downFilePath := filepath.Join(dir, fmt.Sprintf("%s_%s.down.js", version, migrationName))

	if err := fs.WriteFile(upFilePath, []byte(upSQL)); err != nil {
		return fmt.Errorf("failed to write up migration: %w", err)
	}
	if err := fs.WriteFile(downFilePath, []byte(downSQL)); err != nil {
		return fmt.Errorf("failed to write down migration: %w", err)
	}

	fmt.Printf("Generated MongoDB migration: %s\n", upFilePath)
	return nil
}
