package generator

const MigrationTableTemplate = `CREATE TABLE IF NOT EXISTS schema_migrations (
    version VARCHAR(14) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    applied_at TIMESTAMP NOT NULL DEFAULT NOW(),
    rollback_sql TEXT
);`

const PostgresMigrationTemplate = `-- Migration: {{.MigrationName}}
-- Version: {{.Version}}
-- Generated by Blueprint

BEGIN;

CREATE TABLE IF NOT EXISTS {{.TableName}} (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    {{range $i, $col := .Columns}}{{if $i}}, {{end}}{{$col.Name}} {{$col.Type}}{{end}}
    {{if .HasSoftDelete}},deleted_at TIMESTAMP{{end}}
    {{if .HasTimestamps}},created_at TIMESTAMP DEFAULT NOW(),updated_at TIMESTAMP DEFAULT NOW(){{end}}
);

CREATE INDEX IF NOT EXISTS idx_{{.TableName}}_created_at ON {{.TableName}}(created_at);
{{range .Indexes}}
CREATE INDEX IF NOT EXISTS idx_{{$.TableName}}_{{.Name}} ON {{$.TableName}}({{.Columns}});
{{end}}

COMMIT;

-- Rollback SQL
-- {{.RollbackSQL}}
`

const PostgresRollbackTemplate = `-- Rollback: {{.MigrationName}}
-- Version: {{.Version}}

BEGIN;

DROP TABLE IF EXISTS {{.TableName}};

COMMIT;
`

const MongoMigrationTemplate = `// Migration: {{.MigrationName}}
// Version: {{.Version}}
// Generated by Blueprint

db.createCollection("{{.CollectionName}}");

db.{{.CollectionName}}.createIndex({ "_id": 1 });

{{range .Indexes}}
db.{{.CollectionName}}.createIndex({ {{.Fields}} }, { name: "idx_{{.Name}}" });
{{end}}

db.{{.CollectionName}}.insertOne({
    _migration_version: "{{.Version}}",
    _migration_name: "{{.MigrationName}}",
    _applied_at: new Date()
});
`

const MongoRollbackTemplate = `// Rollback: {{.MigrationName}}
// Version: {{.Version}}
// Generated by Blueprint

db.{{.CollectionName}}.drop();
`

type MigrationColumn struct {
	Name string
	Type string
}

type MigrationIndex struct {
	Name    string
	Columns string
	Fields  string
}

type MigrationData struct {
	MigrationName string
	Version       string
	TableName     string
	CollectionName string
	Columns       []MigrationColumn
	Indexes       []MigrationIndex
	HasSoftDelete bool
	HasTimestamps bool
	RollbackSQL   string
}
